uq_method:
  _target_: lightning_uq_box.uq_methods.DeterministicClassification
  model:
    _target_: timm.create_model
    model_name: resnet18
    in_chans: 3
    num_classes: 6
  loss_fn:
    _target_: torch.nn.CrossEntropyLoss
  optimizer:
    _target_: torch.optim.SGD
    _partial_: True
    lr: 0.003