datamodule:
  _target_: tropical_cyclone_dm.TropicalCycloneSequenceDataModule
  root: "/p/project/hai_uqmethodbox/data/tropical_cyclone"
  task: "classification"
  batch_size: 256
  num_workers: 12
  min_wind_speed: 0
  class_bin_size: 5