uq_method:
  _target_: lightning_uq_box.uq_methods.DUEClassification
  feature_extractor:
    _target_: timm.create_model
    model_name: "resnet18"
    num_classes: 10 # number of latent features
    in_chans: 3
  gp_kernel: "RBF"
  n_inducing_points: 300
  input_size: 224
  optimizer:
    _target_: torch.optim.Adam # can change optimizers here easily
    _partial_: true
    lr: 0.0001
  num_classes: 6 # number of target classes

datamodule:
  batch_size: 32