experiment:
  experiment_name: "cyclone"
  exp_dir: "/p/project/hai_uqmethodbox/experiment_output/test_class/"
wandb:
  project: tropical_cyclone_class
  entity: uq-regression
  mode: offline

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu
  min_epochs: 50
  max_epochs: 80
  log_every_n_steps: 20
  enable_progress_bar: Truex
