uq_method:
  _target_: lightning_uq_box.uq_methods.BNN_VI_ELBO_Regression
  model:
    _target_: timm.create_model
    model_name: resnet18
    in_chans: 3
    num_classes: 1
  criterion:
    _target_: torch.nn.CrossEntropyLoss
  num_mc_samples_train: 5
  num_mc_samples_test: 30
  prior_mu: 0.0
  prior_sigma: 1.0
  posterior_mu_init: 0.0
  posterior_rho_init: -3.0
  bayesian_layer_type: "reparameterization"
  beta: 10000
  burnin_epochs: 0
  stochastic_module_names:
  - layer4.1.conv1
  - layer4.1.conv2
  - fc
  optimizer:
    _target_: torch.optim.Adam # can change optimizers here easily
    _partial_: true
    lr: 0.001