datamodule:
  _target_: tropical_cyclone_dm.TropicalCycloneSequenceDataModule
  root: "/p/project/hai_uqmethodbox/data/tropical_cyclone"
  task: "regression"
  batch_size: 128
  num_workers: 12
  min_feature_value:
    wind: 34