uq_method:
  _target_: lightning_uq_box.uq_methods.DER
  model:
    _target_: timm.create_model
    model_name: resnet18
    in_chans: 3
    num_classes: 4 # DER outputs
  lr_scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _partial_: true
    T_max: 100