uq_method:
  _target_: lightning_uq_box.uq_methods.QuantileRegression
  model:
    _target_: timm.create_model
    model_name: resnet18
    in_chans: 3
    num_classes: 3
  loss_fn: 
    _target_: lightning_uq_box.uq_methods.QuantileLoss
    quantiles:
    - 0.1
    - 0.5
    - 0.9