uq_method:
  _target_: lightning_uq_box.uq_methods.BNN_VI_Regression
  model:
    _target_: skippd_model.SkippdModel
    in_chans: 3
    num_classes: 1
  #criterion:
  #  _target_: torch.nn.MSELoss
  n_mc_samples_train: 5
  n_mc_samples_test: 30
  prior_mu: 0.0
  prior_sigma: 6.0
  posterior_mu_init: 0.0
  posterior_rho_init: -1.0
  alpha: 0.9
  bayesian_layer_type: reparameterization
  stochastic_module_names:
  - conv1.1
  - conv2.0
  optimizer:
    _target_: torch.optim.Adam
    _partial_: true
    lr: 0.0001
