uq_method:
  _target_: lightning_uq_box.uq_methods.CARDRegression
  cond_mean_model:
    _target_: lightning_uq_box.uq_methods.utils.checkpoint_loader
    model_class:
      _target_: lightning_uq_box.uq_methods.DeterministicRegression
      model:
        _target_: skippd_model.SkippdModel
        in_chans: 3
        num_classes: 1
      loss_fn:
        _target_: torch.nn.MSELoss
    ckpt_path: /p/project/hai_uqmethodbox/experiment_output/pv_bestof/pv_skippd_DeterministicRegression_05-28-2024_09-56-21-539472/epoch=0-step=816.ckpt
  guidance_model:
    _target_: lightning_uq_box.models.ConditionalGuidedConvModel
    encoder:
      _target_: skippd_model.SkippdModel
      in_chans: 3
      num_classes: 1
    cond_guide_model:
      _target_: lightning_uq_box.models.ConditionalGuidedLinearModel
      n_steps: 200
      x_dim: 1 
      y_dim: 1 
      n_hidden: [128, 128, 128]
      cat_x: false
      cat_y_pred: true
  guidance_optim:
    _target_: torch.optim.Adam
    _partial_: true
    lr: 0.0001
  beta_schedule: "linear"
  n_steps: 200
  n_z_samples: 10

trainer:
  precision: 16-mixed

datamodule:
  batch_size: 128