uq_method:
  _target_: lightning_uq_box.uq_methods.ConformalQR
  model:
    _target_: lightning_uq_box.uq_methods.utils.checkpoint_loader
    model_class:
      _target_: lightning_uq_box.uq_methods.QuantileRegression
      model:
        _target_: skippd_model.SkippdModel
        in_chans: 48
        num_classes: 3
    ckpt_path: /p/project/hai_uqmethodbox/experiment_output/pv_hpo/pv_skippd_QuantileRegression_05-28-2024_09-54-41-628380/epoch=0-step=816.ckpt
    return_model: False
  quantiles:
  - 0.1
  - 0.5
  - 0.9