datamodule:
  _target_: skippd_datamodule.MySKIPPDDataModule
  root: "/p/project/hai_uqmethodbox/data/skippd"
  task: "forecast"
  batch_size: 128
  num_workers: 12
  
  #min_feature_value:
  #  wind: 34
