ensemble_members:
  _target_: lightning_uq_box.uq_methods.MVERegression
  model:
    _target_: skippd_model.SkippdModel
    in_chans: 48
    num_classes: 2
  burnin_epochs: 0

uq_method:
  _target_: lightning_uq_box.uq_methods.DeepEnsembleRegression
  n_ensemble_members: 5
  ensemble_members:
  - /p/project/hai_uqmethodbox/experiment_output/pv_hpo/pv_skippd_MVERegression_05-28-2024_16-37-03-287327/epoch=5-step=4896.ckpt
  - /p/project/hai_uqmethodbox/experiment_output/pv_hpo/pv_skippd_MVERegression_05-28-2024_16-14-54-588535/epoch=5-step=4896.ckpt
  - /p/project/hai_uqmethodbox/experiment_output/pv_hpo/pv_skippd_MVERegression_05-28-2024_16-14-54-588529/epoch=0-step=816.ckpt
  - /p/project/hai_uqmethodbox/experiment_output/pv_hpo/pv_skippd_MVERegression_05-28-2024_16-14-54-588520/epoch=0-step=816.ckpt
  - /p/project/hai_uqmethodbox/experiment_output/pv_hpo/pv_skippd_MVERegression_05-28-2024_16-14-54-588514/epoch=6-step=5712.ckpt