uq_method:
  _target_: lightning_uq_box.uq_methods.DKLRegression
  feature_extractor:
    _target_: /p/project/hai_uqmethodbox/nina/tropical_cyclone_uq/skippd_model.py.Model
    model_name: SkippdModel
    num_classes: 10
    in_chans: 48
  gp_kernel: "RBF"
  n_inducing_points: 300
  optimizer:
    _target_: torch.optim.AdamW
    _partial_: True
    lr: 0.003

datamodule:
  batch_size: 128