uq_method:
  _target_: lightning_uq_box.uq_methods.DKLRegression
  feature_extractor:
    _target_: skippd_model.SkippdModel
    in_chans: 3
    num_classes: 10
  gp_kernel: "RBF"
  n_inducing_points: 50
  optimizer:
    _target_: torch.optim.AdamW
    _partial_: True
    lr: 0.0001

datamodule:
  batch_size: 64