uq_method:
  _target_: lightning_uq_box.uq_methods.DUERegression
  feature_extractor:
    _target_: skippd_model.SkippdModel
    in_chans: 48
    num_classes: 20
  gp_kernel: "RBF"
  n_inducing_points: 200
  input_size: 64
  optimizer:
    _target_: torch.optim.AdamW # can change optimizers here easily
    _partial_: true
    lr: 0.0001

datamodule:
  batch_size: 64