uq_method:
  _target_: lightning_uq_box.uq_methods.LaplaceRegression
  laplace_model:
    _target_: laplace.Laplace
    model:
      _target_: lightning_uq_box.uq_methods.utils.checkpoint_loader
      model_class:
        _target_: lightning_uq_box.uq_methods.DeterministicRegression
        model:
          _target_: skippd_model.SkippdModel
          in_chans: 48
          num_classes: 1
        loss_fn:
          _target_: torch.nn.MSELoss
      ckpt_path: /p/project/hai_uqmethodbox/experiment_output/reg_digital_34/cyclone_DeterministicRegression_03-02-2024_09-58-17-465511/epoch=29-step=15120.ckpt
      return_model: True
    likelihood: "regression"
    sigma_noise: 0.5
    prior_precision: 1.0
    # prior_mean: 0.0
    # temperature: 1.0
    subset_of_weights: "last_layer"
    hessian_structure: "diag"

trainer:
  _target_: lightning.pytorch.Trainer
  inference_mode: False
  # limit_test_batches: 2
  
  