# everything to configure the UQ method
uq_method:
  _target_: lightning_uq_box.uq_methods.MCDropoutRegression
  model:
    _target_: skippd_model.SkippdModel
    in_chans: 3
    num_classes: 2
    drop_rate: 0.1
  loss_fn: 
    _target_: lightning_uq_box.uq_methods.NLL
  optimizer:
    _target_: torch.optim.SGD
    _partial_: True
    lr: 0.0001
  num_mc_samples: 30