# everything to configure the UQ method
uq_method:
  _target_: lightning_uq_box.uq_methods.MCDropoutRegression
  model:
    _target_: /p/project/hai_uqmethodbox/nina/tropical_cyclone_uq/skippd_model.py.Model
    model_name: SkippdModel
    in_chans: 48
    num_classes: 2
    drop_rate: 0.1
  loss_fn: 
    _target_: lightning_uq_box.uq_methods.NLL
  optimizer:
    _target_: torch.optim.Adam
    _partial_: True
    lr: 0.003
  num_mc_samples: 30