uq_method:
  _target_: lightning_uq_box.uq_methods.MVERegression
  model:
    _target_: skippd_model.SkippdModel
    in_chans: 48
    num_classes: 2
  burnin_epochs: 0
  optimizer:
    _target_: torch.optim.Adam
    _partial_: True
    lr: 0.0001