uq_method:
  _target_: lightning_uq_box.uq_methods.QuantileRegression
  model:
    _target_: skippd_model.SkippdModel
    in_chans: 48
    num_classes: 3
  loss_fn: 
    _target_: torch.nn.HuberLoss
    quantiles:
    - 0.05
    - 0.5
    - 0.95
  optimizer:
    _target_: torch.optim.SGD
    _partial_: True
    lr: 0.0001