uq_method:
  _target_: lightning_uq_box.uq_methods.SWAGRegression
  model:
    _target_: lightning_uq_box.uq_methods.utils.checkpoint_loader
    model_class:
        _target_: lightning_uq_box.uq_methods.MVERegression
        model:
          _target_: skippd_model.SkippdModel
          in_chans: 3
          num_classes: 2
        burnin_epochs: 0
    ckpt_path: /p/project/hai_uqmethodbox/experiment_output/pv_hpo/pv_skippd_MVERegression_05-28-2024_09-56-21-539464/epoch=0-step=816.ckpt
    return_model: True

  max_swag_snapshots: 50
  snapshot_freq: 1
  num_mc_samples: 30
  swag_lr: 0.0004
  loss_fn:
    _target_: lightning_uq_box.uq_methods.NLL
  num_datapoints_for_bn_update: 0
  stochastic_module_names:
  - conv1.1
  - conv2.0

trainer:
  _target_: lightning.pytorch.Trainer
  min_epochs: 1
  max_epochs: 10 # number of swag epochs