experiment:
  experiment_name: "pv_skippd"
  exp_dir: "/p/project/hai_uqmethodbox/experiment_output/pv_hpo/"
wandb:
  project: digital_typhoon
  entity: uq-regression
  mode: online

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu
  min_epochs: 0
  max_epochs: 7
  log_every_n_steps: 10
  enable_progress_bar: True

#imagenet_ckpt: /p/project/hai_uqmethodbox/data/resnet18.ckpt
# imagenet_ckpt: /p/project/hai_uqmethodbox/data/efficientnet_b0.ckpt
